/* This file is automatically generated by Makefile.PL.
   Don't edit this file, since any changes will be lost */

#ifndef IMAGER_IMCONFIG_H
#define IMAGER_IMCONFIG_H

/*
  Logging system
*/

#define IMAGER_LOG 1

/*
  Parsed giflib version
*/

#define IM_GIFMAJOR 4
#define IM_GIFMINOR 0

/*
  gif available
*/

#define HAVE_LIBGIF 1

/*
  jpeg available
*/

#define HAVE_LIBJPEG 1

/*
  png available
*/

#define HAVE_LIBPNG 1

/*
  Enable experimental EXIF support
*/

#define IMEXIF_ENABLE 1

#endif
